import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { LandingGrid } from '../components/landing/LandingGrid'

const IndexPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ height: '100vh', width: '100%' }}>
        <LandingGrid />
      </main>
    </div>
  )
}

export default IndexPage
